name: nightly

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # Every night at 03:00
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: passsy/flutterw:base-0.4.1

    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          mkdir -p /flutter
          git clone https://github.com/flutter/flutter.git -b stable /flutter
          export PATH="$PATH:/flutter/bin"
          echo "/flutter/bin" >> $GITHUB_PATH
          cat /flutter/.git/config
          # TODO fetch this in flutterw script
          git -C /flutter fetch origin
          git -C /flutter fetch --all
          flutter precache --linux --web
          
          git config --global user.email "dash@flutter.io"
          git config --global user.name "Dash"
      - run: |
          cd test
          dart pub get
      - run: |
          cd test
          dart run test

  createSampleProject:
    runs-on: ubuntu-latest

    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter create sample
          cd sample
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/passsy/flutter_wrapper/master/install.sh)"
      - uses: actions/upload-artifact@v2
        with:
          name: sample
          path: sample

  build_on_linux:
    runs-on: ubuntu-latest
    needs: createSampleProject

    container:
      # Use container with pre-installed Flutter dependencies like unzip, libglu1-mesa
      image: passsy/flutterw:base-0.4.1

    steps:
      - uses: actions/checkout@v2.4.0
      - run: ./flutterw doctor -v
      - run: ./flutterw pub get
      - run: ./flutterw test
      - run: ./flutterw analyze --fatal-infos --fatal-warnings .

  build_on_macos:
    runs-on: macos-latest
    needs: createSampleProject

    steps:
      - uses: actions/checkout@v2.4.0
      - run: ./flutterw doctor -v
      - run: ./flutterw pub get
      - run: ./flutterw test
      - run: ./flutterw analyze --fatal-infos --fatal-warnings .
